test: hello application.yml
yx:
  name: yx
  age: 22
  sex: 男

spring:
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
      profile: dev
  application:
    name: config-client